# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

import site
import sys
site.ENABLE_USER_SITE = "--user" in sys.argv[1:]

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='transformation_algebra',
    version='0.0.0',
    packages=['transformation_algebra'],
    package_dir={"": "."},
    package_data={"transformation_algebra": ["*.typed"]},
    install_requires=['setuptools>=42', 'wheel'],
)
